services:

  application:
    image: nagarajukuruva/travelappimage:latest
    ports:
      - "1111:8080"
    networks:
      - appnetwork
    volumes:
      - appvolume:/app
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "0.5"
          memory: 300M
        limits:
          cpus: "1"
          memory: 500M
    depends_on:
      - database

  database:
    image: nagarajukuruva/traveldbimage:latest
    ports:
      - "3306:3306"
    networks:
      - appnetwork
    volumes:
      - dbvolume:/var/lib/mysql
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "0.5"
          memory: 300M
        limits:
          cpus: "1"
          memory: 500M

networks:
  appnetwork:
    driver: overlay
    attachable: true

volumes:
  appvolume:
  dbvolume:
