---
services:
  appilcation:
    container_name: appcont
    build: .
    ports:
      - "1111:8080"
    networks:
      - appnetwork
    volumes:
      - appvolume:/app
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 300M
        limits:
          cpus: "1"
          memory: 500M
    depends_on:
      - database
  database:
    container_name: dbcont
    build: ./db/
    ports:
      - "3306:3306"
    networks:
      - appnetwork
    volumes:
      - dbvolume:/var/lib/mysql
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 300M
        limits:
          cpus: "1"
          memory: 500M
networks:
  appnetwork:
    driver: overlay
    attachable: true
volumes:
  appvolume:
  dbvolume:  
